// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using activity_center.Models;

namespace activity_center.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20191017191432_DojoActivityMigration")]
    partial class DojoActivityMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("activity_center.Models.Rsvp", b =>
                {
                    b.Property<int>("RsvpId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("TheActivityId");

                    b.Property<int>("UserId");

                    b.HasKey("RsvpId");

                    b.HasIndex("TheActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("activity_center.Models.TheActivity", b =>
                {
                    b.Property<int>("TheActivityId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ActivityDate");

                    b.Property<int>("UserId");

                    b.Property<string>("description")
                        .IsRequired();

                    b.Property<int>("duration");

                    b.Property<string>("duration_unit")
                        .IsRequired();

                    b.Property<string>("time")
                        .IsRequired();

                    b.Property<string>("title")
                        .IsRequired();

                    b.HasKey("TheActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("activity_center.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("confirm_password");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("first_name")
                        .IsRequired();

                    b.Property<string>("last_name")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("activity_center.Models.Rsvp", b =>
                {
                    b.HasOne("activity_center.Models.TheActivity", "TheActivity")
                        .WithMany("Attending")
                        .HasForeignKey("TheActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("activity_center.Models.User", "User")
                        .WithMany("Action")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("activity_center.Models.TheActivity", b =>
                {
                    b.HasOne("activity_center.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
